### PR TITLE
Map on node pages take 2

### PR DESCRIPTION
**Pull request by timstallmann**
@AnneTee here's how i was thinking we might could do it -- what do you think? I can't figure out how to store the node title in a JS variable though.

### CODE REVIEW

**Comment by AnneTee** [comment]
@timstallmann I like that it's centered on the point and at a higher zoom level. I still think it'd be nice to have the popup open if nothing else because it's visually pleasing.

**Comment by timstallmann** [comment]
@AnneTee I agree! I just can't figure out how to set a JS variable equal to the node title w/in twig.. any ideas? I tried just doing

```
var nodeTitle = "{{ title }}";
```

and it didn't like that

**Comment by AnneTee** [comment]
Oh gotcha :)

I'm happy to look into it more tomorrow, but I have a hunch that it may not be possible because They don't want you using JS in Twig templates.

**Comment by timstallmann** [comment]
But it worked fine with lat and lon!!

**Comment by timstallmann** [comment]
@AnneTee maybe this is just back to where we started a long time ago but I got the map to appear back on node pages. Still to-do is getting the point labeled or with some kind of popup open.

Would love your input on _where_ the map should actually show up on node pages? They're getting kinda crowded now, esp. once the soundcloud player gets added in.

**Comment by AnneTee** [comment]
@timstallmann The original plan was to place a large map at the bottom of the page. See the prototype below.

One thing we could do to justify such a large map is include all the points but have the node's popup open. That way people can easily navigate to other node pages. What do you think?

screen shot 2015-09-23 at 5 19 51 pm

**Comment by timstallmann** [comment]
ok @AnneTee I think this is ready to take a look at too!

**Comment by timstallmann** [comment]
@AnneTee are we good to merge this now?

**Comment by AnneTee** [comment]
@timstallmann Yep! Merge away

**Pull request merged**
