### PR TITLE
Stub out "mappy" theme

### PR DESCRIPTION
**Pull request by timstallmann**
This PR does the following:
- Creates a new theme, called mappy
- Adds compass support
- Creates a basic SMACCS directory structure
- Adds stripped-down template files for page--frontpage and page--node
- Does some simple responsive styling for page--frontpage

@AnneTee could you do some QA on this and also give your opinion about whether it might be easier to switch over to using an existing grid framework? 

I suppose we could also bring in a grid framework just for the individual node pages and keep a custom layout on the frontpage with the map.

### CODE REVIEW

**Comment by chrisarusso** [comment]
@timstallmann did we make a new custom theme? If so, I imagine it should be same convention in D8 to be in a `docroot/sites/all/themes/custom` directory rather than `docroot/themes/` I apologize for my ignorance if I'm wrong :jack_o_lantern:

**Comment by timstallmann** [comment]
Hey @chrisarusso it was my understanding that in D8 custom/contrib modules and themes go in `docroot/themes` and `docroot/modules`; though I could certainly be wrong!

**Comment by chrisarusso** [comment]
The answer lyeth in the twittosphere: :bird: https://twitter.com/Savas_Labs/status/605475295920029696

**Comment by AnneTee** [comment]
@timstallmann Awesome!! I made some changes but I don't have push access to your fork of this repo so I'm going to merge this in then open a new PR for YOU to review. 'Cause I'm mappy.

**Pull request merged**
