### PR TITLE
Theming

### PR DESCRIPTION
**Pull request by AnneTee**
@timstallmann A few odds and ends here:
1. [#207](https://pm.savaslabs.com/issues/207) - added a field to place nodes called "post written by." I realize this is the worst name ever but I was frustrated and "author" didn't work and that's just what it's called now ok?
2. [#295](https://pm.savaslabs.com/issues/295) - fixed the highlight on the search input on /list
3. I also fixed a bug with the map search results to make sure the entire body of the node is hidden

### CODE REVIEW

**Comment by timstallmann** [comment]
@AnneTee locally I'm seeing the `By` label appear even where this field is blank. Any ideas?

**Comment by AnneTee** [comment]
@timstallmann Great point! I've been unable to solve this so far. Maybe we can look at this together sometime.

My understanding was that this would only print the markup if the variable was set:

```
    {% if content.post_written_by %}
      <div class="post_author">
        <h3>By {{ content.post_written_by }}</h3>
      </div>
    {% endif %}
```

Obviously that's not what's happening. I've also tried useing "is not empty" and "is defined" (see [item 4 in this article](https://www.drupal.org/node/1918824) to no avail. Wondering if I'm not using the template properly or if this is a bug that's been fixed in later versions of Drupal. I'd be interested to hear your thoughts!

**Comment by timstallmann** [comment]
@AnneTee is there a reason to do the caption in the template at all vs. putting it as the field label and displaying the label in-line?

**Comment by AnneTee** [comment]
@timstallmann A very good idea, but now the "By" field label is showing up regardless of whether or not the field is populated 0_o

We definitely need to fix this so I'll try to look into it more later this week.

**Comment by timstallmann** [comment]
huh! on my end it worked properly when I tried switching it out just briefly :{{

**Comment by AnneTee** [comment]
Closing, will open a new PR without the author field commits

**Comment by AnneTee** [comment]
Closing this due to too much rebase junkiness, plus there was further theming work to be done. I've reproduced the changes in a better way and will open a new PR.

**Pull request closed without merging**
