### PR TITLE
Making this look like an actual website

### PR DESCRIPTION
**Pull request by AnneTee**
@timstallmann 
- Added Bourbon and Neat
- Added a bunch of base styles - variables, fonts, Neat settings, started adding HTML element styles
- Cleaned up the front page a whole bunch

### CODE REVIEW

**Comment by timstallmann** [comment]
Yay! So nice to see this coming together; great work @AnneTee!
I'm not seeing anything responsive happen with the sidebar on Chrome.. is it working for you?

**Comment by AnneTee** [comment]
@timstallmann no, it's not acting responsive. i'll take a look at that next.

**Comment by AnneTee** [comment]
@timstallmann I've done a lot of refactoring and styling.
- Got the navigation working (still some work to do since the page title is so large)
- edited the front page and node/nodepage layouts and styles
- added the devel module (added this into the codebase since my devel config was exported anyway)

I'm working on styling the nodepage next.

**Comment by timstallmann** [comment]
Yay this is such a great framework to keep developing off of :star2: :stars: :rainbow:

**Pull request merged**
