### PR TITLE
Upgrade to D8 RC1

### PR DESCRIPTION
**Pull request by timstallmann**
You will need also a DB, available here
https://drive.google.com/a/savaslabs.com/file/d/0B1JP94WacpNfb1R4U1JycFRKTk0/view?usp=sharing

To install this locally:
1. _backup your existing DB!!!!_
2. grab the code, edit settings.php to match your local DB name
3. run drush sql-drop and then import the new db
4. will it work? who knows???

### CODE REVIEW

**Comment by AnneTee** [comment]
@timstallmann additional steps I took to get the site to load:
1. Copied the new `examples.settings.local.php` file into my `settings.local.php` file
2. Ran `composer global update`, then `composer install` within the pmp directory to get Drush working
3. Used `drush upwd` to update admin password since `drush sqlsan` still isn't working

The front page isn't showing up for me so I went into `/admin/config/system/site-information` and am getting the following error:

```
InvalidArgumentException: Source path node/6 has to start with a slash. in Drupal\Core\Path\AliasManager->getAliasByPath() (line 194 of core/lib/Drupal/Core/Path/AliasManager.php). 
```

**Comment by AnneTee** [comment]
@timstallmann  looks like we're not the only ones https://www.drupal.org/node/2569117

**Comment by timstallmann** [comment]
@AnneTee thanks for tracking that down! On my end, I'm getting it to work by:
1. Create a new basic page node with the welcome page content,
2. Manually edit the node path in `/config/staging/system.site.yml` to be the path to that node, starting with a slash (e.g. `/node/3`
3. Run `drush config-import staging`

@AnneTee I'm assuming that once you're done with the manual config changes we'll have both a new DB dump and updated config files so rather than put this change into the PR I'll leave it for your update (since the node path will probably change).

**Comment by timstallmann** [comment]
Also just pushed a change to fix the map on the homepage because now apparently JSON feeds need to have the format specified via `?_format=json`.

See http://www.metaltoad.com/blog/why-drupal-8-wont-ship-with-REST-content-negotiation

**Comment by timstallmann** [comment]
@AnneTee I'm going to go ahead and merge this and update the pmp.savasdev.com since it's functional enough for content entry, and then we can build from there.

**Pull request merged**
